version: '3'
services:
    postgres:
        image: 'postgres:latest'
        environment:
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - POSTGRES_PASSWORD=postgres_password
            - PGPORT=5432
    redis:
        image: 'redis:latest'
    server:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            - /app/node_modules
            - ./server:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379

            